sudo: false
language: node_js
node_js:
  - "6"
cache: yarn
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=lodash USE_LODASH=1
after_install:
  - yarn install travis-ci
script:
  - if [[ $TEST_SUITE = "coverage" ]]; then yarn run coveralls; fi
  - if [[ $TEST_SUITE = "lodash" ]]; then yarn run test; fi

